# Generated by Django 5.0.3 on 2024-03-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act_name', models.CharField(max_length=200)),
                ('act_date_delivery', models.DateTimeField()),
                ('act_score', models.IntegerField(default=0)),
                ('act_priority', models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=20)),
                ('act_description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=90)),
                ('user_email', models.CharField(blank=True, max_length=100, unique=True)),
                ('user_university', models.CharField(max_length=70)),
                ('user_carrer', models.CharField(max_length=80)),
                ('user_graduated', models.DateField()),
                ('user_status', models.CharField(choices=[('activo', 'Activo'), ('desactivado', 'Desactivado')], default='activo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
