# Generated by Django 5.0.3 on 2024-03-26 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='act_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.user'),
        ),
    ]
