# Generated by Django 5.0.3 on 2024-04-01 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_activities_act_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
