# Generated by Django 5.0.3 on 2024-04-01 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_user_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserTable',
        ),
    ]
