# Generated by Django 5.0.4 on 2024-04-19 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_rename_user_usertable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docu_title', models.CharField(max_length=255)),
                ('docu_description', models.TextField(max_length=255)),
                ('docu_link', models.TextField(max_length=255)),
                ('docu_file', models.FileField(upload_to='documents/')),
                ('docu_image', models.FileField(upload_to='images/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('docu_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.usertable')),
            ],
        ),
    ]
