# Generated by Django 5.0.4 on 2024-04-19 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='act_category',
            field=models.CharField(default='undefined', max_length=255),
        ),
    ]
